version: '3.8'

services:
  web:
    build:
      context: ./crm_project
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./crm_project:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings
      - DJANGO_ENV=development
    depends_on:
      - redis

  celery:
    build:
      context: ./crm_project
      dockerfile: Dockerfile
    command: celery -A crm_project worker -l INFO
    volumes:
      - ./crm_project:/app
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings
      - DJANGO_ENV=development
    depends_on:
      - web
      - redis

  celery-beat:
    build:
      context: ./crm_project
      dockerfile: Dockerfile
    command: celery -A crm_project beat -l INFO
    volumes:
      - ./crm_project:/app
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings
      - DJANGO_ENV=development
    depends_on:
      - web
      - redis

  trading-bot:
    build:
      context: ./crm_project
      dockerfile: Dockerfile.trading
    volumes:
      - ./crm_project:/app
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings
      - DJANGO_ENV=development
      - IB_HOST=host.docker.internal
      - IB_PORT=7496
      - IB_CLIENT_ID=1
    network_mode: "host"
    depends_on:
      - web
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  default:
    name: app-network 