services:
  web:
    build:
      context: ./crm_project
      dockerfile: dockerfiles/Dockerfile.web
    command: >
      bash -c "
        mkdir -p /app/static /app/logs &&
        echo 'Waiting for database to start...' &&
        sleep 5 &&
        find . -path \"*/migrations/*.py\" -not -name \"__init__.py\" -delete &&
        find . -path \"*/migrations/*.pyc\" -delete &&
        echo 'Creating migrations for signals app...' &&
        python manage.py makemigrations signals &&
        echo 'Creating migrations for trading_bot app...' &&
        python manage.py makemigrations trading_bot &&
        echo 'Applying migrations...' &&
        python manage.py migrate &&
        echo 'Starting Django server...' &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./crm_project:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings
      - DJANGO_ENV=development
    depends_on:
      - redis
    networks:
      - app-network

#  celery:
#    build:
#      context: ./crm_project
#      dockerfile: dockerfiles/Dockerfile.celery
#    volumes:
#      - ./crm_project:/app
#    environment:
#      - DJANGO_SETTINGS_MODULE=crm_project.settings
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - CELERY_RESULT_BACKEND=redis://redis:6379/0
#    depends_on:
#      - redis
#      - web
#    networks:
#      - app-network

  celery-bot:
    build: 
      context: ./crm_project
      dockerfile: dockerfiles/Dockerfile.celery-bot
    volumes:
      - ./crm_project:/app
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - IB_HOST=host.docker.internal
      - IB_PORT=4002
      - IB_CLIENT_ID=1234
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - app-network

  celery-signals:
    build: 
      context: ./crm_project
      dockerfile: dockerfiles/Dockerfile.celery-signals
    volumes:
      - ./crm_project:/app
    depends_on:
      - web
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    restart: unless-stopped
    networks:
      - app-network

  celery-beat:
    build:
      context: ./crm_project
      dockerfile: dockerfiles/Dockerfile.celery-beat
    volumes:
      - ./crm_project:/app
    environment:
      - DJANGO_SETTINGS_MODULE=crm_project.settings
      - DJANGO_ENV=development
    depends_on:
      - web
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge 