# Dockerfile.celery-signals
FROM python:3.11-slim
WORKDIR /app

# Установка curl для проверки доступности web-сервиса
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
ENV PYTHONPATH=/app
ENV DJANGO_SETTINGS_MODULE=crm_project.settings
CMD ["celery", "-A", "crm_project", "worker", "-l", "INFO", "-Q", "signals_queue"]