# Используем официальный образ Python
FROM python:3.11-slim

# Установка curl для проверки доступности web-сервиса
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код проекта
COPY . .

# Запускаем Celery beat
CMD ["celery", "-A", "crm_project", "beat", "-l", "INFO"] 