# Используем официальный образ Python
FROM python:3.11-slim

# Установка curl для healthcheck
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код проекта
COPY . .

# Запускаем команду по умолчанию (будет переопределена в docker-compose.yml)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"] 