# Generated by Django 5.2 on 2025-04-06 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние бота',
                'verbose_name_plural': 'Состояние бота',
            },
        ),
        migrations.CreateModel(
            name='BotSeasonalSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(help_text='Дата и время входа в позицию', verbose_name='Дата входа')),
                ('exit_date', models.DateTimeField(help_text='Дата и время выхода из позиции', verbose_name='Дата выхода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting'), ('open', 'Trade Open'), ('close', 'Trade Close')], default='awaiting', max_length=10)),
                ('order_id', models.IntegerField(blank=True, help_text='ID ордера в Interactive Brokers', null=True, verbose_name='ID ордера')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_signals', to='signals.seasonalsignal', verbose_name='Сезонный сигнал')),
            ],
            options={
                'verbose_name': 'Торговый сигнал',
                'verbose_name_plural': 'Торговые сигналы',
                'ordering': ['-created_at'],
            },
        ),
    ]
