# Generated by Django 4.2 on 2025-03-27 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("signals", "0004_create_symbol_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSeasonalSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_date",
                    models.DateTimeField(
                        help_text="Дата и время входа в позицию",
                        verbose_name="Дата входа",
                    ),
                ),
                (
                    "exit_date",
                    models.DateTimeField(
                        help_text="Дата и время выхода из позиции",
                        verbose_name="Дата выхода",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_signals",
                        to="signals.seasonalsignal",
                        verbose_name="Сезонный сигнал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Торговый сигнал",
                "verbose_name_plural": "Торговые сигналы",
                "ordering": ["-created_at"],
            },
        ),
    ]
