# Generated by Django 5.1.7 on 2025-03-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botseasonalsignal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Trade Open'), ('close', 'Trade Close')], default='pending', max_length=10, verbose_name='Trade Status'),
        ),
    ]
