# Generated by Django 5.1.7 on 2025-03-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0002_botseasonalsignal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botseasonalsignal',
            name='status',
            field=models.CharField(choices=[('awaiting', 'awaiting'), ('open', 'Trade Open'), ('close', 'Trade Close')], default='awaiting', max_length=10, verbose_name='Trade Status'),
        ),
    ]
