# Generated by Django 5.1.7 on 2025-03-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0003_alter_botseasonalsignal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botseasonalsignal',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('open', 'Trade Open'), ('close', 'Trade Close')], default='awaiting', max_length=10),
        ),
    ]
