# Generated by Django 5.1.7 on 2025-03-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0004_alter_botseasonalsignal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='botseasonalsignal',
            name='order_id',
            field=models.IntegerField(blank=True, help_text='ID ордера в Interactive Brokers', null=True, verbose_name='ID ордера'),
        ),
    ]
