# Generated by Django 5.2 on 2025-04-07 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_instrument', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Symbol',
                'verbose_name_plural': 'Symbols',
                'ordering': ['financial_instrument'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magic_number', models.IntegerField(error_messages={'unique': 'Сигнал с таким Magic Number уже существует'}, unique=True)),
                ('stoploss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stoploss_type', models.CharField(choices=[('POINTS', 'Points'), ('PERCENTAGE', 'Percentage')], default='POINTS', max_length=10)),
                ('risk', models.DecimalField(decimal_places=2, max_digits=5)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=5)),
                ('entry_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('entry_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('takeprofit_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('takeprofit_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='signals.symbol', verbose_name='Symbol')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
