# Generated by Django 4.2 on 2025-03-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0002_alter_seasonalsignal_magic_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seasonalsignal",
            name="month",
        ),
    ]
