# Generated by Django 4.2 on 2025-03-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("signals", "0003_remove_month_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_instrument", models.CharField(max_length=50, unique=True)),
                ("company_name", models.CharField(max_length=100)),
                ("exchange", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Символ",
                "verbose_name_plural": "Символы",
                "ordering": ["financial_instrument"],
            },
        ),
        migrations.AlterField(
            model_name="seasonalsignal",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="signals.symbol",
                verbose_name="Символ",
            ),
        ),
    ]
